{% set name = "codeguru_profiler_agent" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb4181a815dd57bca600711dec2cc689bc9a59426ca127b5f8ea96c88bac856f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3 >=1.14.0
    - python >=3.6

test:
  imports:
    - codeguru_profiler_agent
    - codeguru_profiler_agent.agent_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html
  summary: The Python agent to be used for Amazon CodeGuru Profiler
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html
  dev_url: https://github.com/aws/amazon-codeguru-profiler-python-agent

extra:
  recipe-maintainers:
    - BastianZim
